version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cloud_postgres
    restart: always
    environment:
      POSTGRES_DB: cloud_storage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
